### ISSUE TITLE
Almost impossible to pass area

### ISSUE THREAD

**Issue by ghost** [orionfuzion/newcracks#2]
![problem area](https://github.com/orionfuzion/newcracks/assets/108537065/559fa673-bbe9-47b2-88c2-60e2a2a1e014)
Hi!

First of all, my respect for the great work you have done. Really fantastic.
My following question is not a bug but "another problem".
There is one very difficult sea level area in the game that is almost impossible to pass, trainer does not help in this case as it concerns jumping platforms.
I was not able to pass this area myself and I see a lot of Youtube video's of where people struggle also not passing.
Look at the following Youtube video at 38:36: (the guy cannot pass this area also)
https://www.youtube.com/watch?v=Lc_6ru8O0Jk&t=623s

Could you do something about that? To make that platform wider or fixed so that we could cross it? Maybe a super jump option in the trainer with repeated/multiple jumps?

As said, great work that you have done!
Kind regards, Hans from Belgium.

**Comment by orionfuzion** [comment]
Hi Hans!

Sorry for my very late reply, but I've only just discovered your message.

In this game, you have to find hidden doors that lead to "bonus rooms" where you can collect money, or to "secret passages" that allow you to reach locations that would otherwise be inaccessible.

In the specific case you describe, here's the entrance to a secret passage, whose door is hidden by default:

![Secret Passage Door](https://github.com/orionfuzion/newcracks/assets/24521796/5ef58dc6-522f-43ca-aed6-8d5173c418f0)

To make this door appear, you need to fire at his location several times until it appears.

Here's what you can expect when you walk through that door:

![grab0002](https://github.com/orionfuzion/newcracks/assets/24521796/a351f50d-9d42-4456-bf09-280ec79e0bca)
![grab0003](https://github.com/orionfuzion/newcracks/assets/24521796/b769edd1-172e-4e5d-9d7f-1109cab08521)

And when you leave that secret passage, you arrive at the location you were trying to reach:

![grab0004](https://github.com/orionfuzion/newcracks/assets/24521796/1b190e8a-fa4d-47da-92b2-f30ebb2491a7)

Good luck for the rest of the game.

The Replicants Rulez!!

-- Orion

**Comment by ghost** [comment]
Thank you for such a clear explanation. I did not know this. 😊

 

Thank you for the great work guy’s!

 

Van: Orion ***@***.***> 
Verzonden: donderdag 7 december 2023 0:14
Aan: orionfuzion/newcracks ***@***.***>
CC: Hooky72 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [orionfuzion/newcracks] Almost impossible to pass area (Issue #2)

 

Hi Hans!

Sorry for my very late reply, but I've only just discovered your message.

In this game, you have to find hidden doors that lead to "bonus rooms" where you can collect money, or to "secret passages" that allow you to reach locations that would otherwise be inaccessible.

In the specific case you describe, here's the entrance to a secret passage, whose door is hidden by default:

grab0001.png (view on web) <https://github.com/orionfuzion/newcracks/assets/24521796/5ef58dc6-522f-43ca-aed6-8d5173c418f0> 

To make this door appear, you need to fire at his location several times until it appears.

Here's what you can expect when you walk through that door:

grab0002.png (view on web) <https://github.com/orionfuzion/newcracks/assets/24521796/a351f50d-9d42-4456-bf09-280ec79e0bca> 
grab0003.png (view on web) <https://github.com/orionfuzion/newcracks/assets/24521796/b769edd1-172e-4e5d-9d7f-1109cab08521> 

And when you leave that secret passage, you arrive at the location you were trying to reach:

grab0004.png (view on web) <https://github.com/orionfuzion/newcracks/assets/24521796/1b190e8a-fa4d-47da-92b2-f30ebb2491a7> 

Good luck for the rest of the game.

The Replicants Rulez!!

-- Orion
